export enum Agent {
  BRIMSTONE = 'Brimstone',
  VIPER = 'Viper',
  ASTRA = 'Astra',
  JETT = 'Jett',
  RAZE = 'Raze',
  REYNA = 'Reyna',
  BREACH = 'Breach',
  CHAMBER = 'Chamber',
  CYPHER = 'Cypher',
  KILLJOY = 'Killjoy',
  KAYO = 'Kayo',
  SOVA = 'Sova',
  YORU = 'Yoru',
  NEON = 'Neon',
  OMEN = 'Omen',
  PHOENIX = 'Phoenix',
  SAGE = 'Sage',
}
